### ISSUE TITLE
Crashing on Valoria-1.20.1 (0.6.3b)

### ISSUE THREAD

**Issue by SHXRKIEgg** [IriDark/Valoria#14]
### Issue

Opened a Sarcophagus and Crashed with Mods and Standalone

### Steps to reproduce

Opened a Sarcophagus and Crashes

### Build

Valoria-1.20.1 (0.6.3b)

### Mods used

Tested both in my Modpack and Standalone
Crashlog should show all the Mods (Developer of LPS here and going to use this mod our Otherworld Modpack coming out soon)

### Crashlogs

Standalone w/ Dependancies:
[crash-2024-10-22_13.00.09-client.txt](https://github.com/user-attachments/files/17470306/crash-2024-10-22_13.00.09-client.txt)

With Modpack:
[crash-2024-10-22_12.49.04-client.txt](https://github.com/user-attachments/files/17470237/crash-2024-10-22_12.49.04-client.txt)

### Submission

- [X] I have updated to the latest version to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by IriDark** [comment]
You can download version with fix here - https://github.com/IriDark/Valoria/releases/tag/DevBuild
Currently it's not available to public

**Comment by SHXRKIEgg** [comment]
Also fails to load correctly on server
