### ISSUE TITLE
Cannot create world

### ISSUE THREAD

**Issue by medsal15** [IriDark/Valoria#16]
### Issue

The biomes appear to attempt to load the mood `minecraft:nether_wastet.mood`, which does not exist. As a result, minecraft refuses to load/create any world.

### Steps to reproduce

Join existing world
Minecraft refuses to load the world

### Build

0.6.4.16

### Submission

- [X] I have updated to the latest version to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by IriDark** [comment]
Fix will be published later as a hotfix, weird that it's causes a crash

**Comment by IriDark** [comment]
![image](https://github.com/user-attachments/assets/c398659c-e9a6-4e71-a6a8-c7f58322a7aa)
