### ISSUE TITLE
суккубы занимают весь спавнрейт и не имеют дропов

### ISSUE THREAD

**Issue by Auriny** [IriDark/Valoria#20]
### Issue

их слишком много 

### Steps to reproduce

-

### Build

0.6.4.18

### Submission

- [ ] I have updated to the latest version to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by IriDark** [comment]
дроп не является ошибкой а скорее штукой на будущее
