### ISSUE TITLE
elemental manipulator gui works weirdo

### ISSUE THREAD

**Issue by Auriny** [IriDark/Valoria#26]
### Issue

![image](https://github.com/user-attachments/assets/4aa70590-3ae6-42d8-8bb7-64f2ee80a676)

### Steps to reproduce

-

### Build

0.6.4.21

### Submission

- [x] I have updated to the latest version to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by IriDark** [comment]
![image](https://github.com/user-attachments/assets/8675f56f-9e76-40a3-a0cd-99882749ab43)
um

**Comment by IriDark** [comment]
cannot reproduce
![image](https://github.com/user-attachments/assets/f1d6de20-a0d5-4817-9b31-08679e193c95)
