### ISSUE TITLE
Crypt chest loot table is broken

### ISSUE THREAD

**Issue by Not-February** [IriDark/Valoria#28]
### Issue

The item `valoria:muramasa_trim` is an entry in the loot table, but this item doesn't exist in the mod anymore, so the chests in crypts are empty.

### Steps to reproduce

Open chests in the crypt structure

### Build

0.6.4.17

### Submission

- [X] I have updated to the latest version to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by IriDark** [comment]
has been fixed, thanks
